//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdentityFederation.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IdentityFederation.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.xmlsoap.org/claims/CommonName.
        /// </summary>
        internal static string CommonNameClaim {
            get {
                return ResourceManager.GetString("CommonNameClaim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress.
        /// </summary>
        internal static string EmailaddressClaim {
            get {
                return ResourceManager.GetString("EmailaddressClaim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.xmlsoap.org/ws/2005/05/identity/claims/givenname.
        /// </summary>
        internal static string GivennameClaim {
            get {
                return ResourceManager.GetString("GivennameClaim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The incoming token did not have any Claims..
        /// </summary>
        internal static string NoClaims {
            get {
                return ResourceManager.GetString("NoClaims", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IClaimsIdentity does not contain a nameidentifier claim..
        /// </summary>
        internal static string NoNameidentifier {
            get {
                return ResourceManager.GetString("NoNameidentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.microsoft.com/ws/2008/06/identity/claims/organization.
        /// </summary>
        internal static string OrganizationClaim {
            get {
                return ResourceManager.GetString("OrganizationClaim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.xmlsoap.org/ws/2005/05/identity/claims/otherphone.
        /// </summary>
        internal static string OtherphoneClaim {
            get {
                return ResourceManager.GetString("OtherphoneClaim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://schemas.xmlsoap.org/ws/2005/05/identity/claims/surname.
        /// </summary>
        internal static string SurnameClaim {
            get {
                return ResourceManager.GetString("SurnameClaim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SimpleWebToken is expected..
        /// </summary>
        internal static string SwtExpected {
            get {
                return ResourceManager.GetString("SwtExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Issuer &apos;{0}&apos; is unknown..
        /// </summary>
        internal static string UnknownIssuer {
            get {
                return ResourceManager.GetString("UnknownIssuer", resourceCulture);
            }
        }
    }
}
