{
    "NodeValuationSet":
    [
        {"MeasureSet":["1"],"MaxValuation":0.05},
        {"MeasureSet":["2"],"MaxValuation":0.25},
        {"MeasureSet":["3"],"MaxValuation":0.38},
        {"MeasureSet":["1","2"],"MaxValuation":1.85},
        {"MeasureSet":["1","3"],"MaxValuation":1.98},
        {"MeasureSet":["2","3"],"MaxValuation":8.40},
        {"MeasureSet":["1","2","3"],"MaxValuation":10.00}
    ]
}